### ISSUE TITLE
正则表达式入门笔记 | 李小朋的博客

### ISSUE THREAD

**Issue by LiJiaPeng001** [LiJiaPeng001/LiJiaPeng001.github.io#2]
https://lijiapeng001.github.io/2018/12/24/reg/ 

 正则一直是我弱项，闲着没事写笔记学习吧~ RegExp对象js的内置对象RegExp支持正则表达式有两种方法实例化RegExp对象  字面量    var reg = /a/ 构造函数   var reg = new RegExp(‘/a/‘)  修饰符 g:global全局搜索，不添加，搜索到第一个停止 i:ignore case 忽略大小写，默认大小写敏感 m:multiple lines 多

**Comment by LiJiaPeng001** [comment]
大家来测试一下评论

**Comment by betterLeaf** [comment]
123
