### ISSUE TITLE
2019 | 李小朋的博客

### ISSUE THREAD

**Issue by LiJiaPeng001** [LiJiaPeng001/LiJiaPeng001.github.io#3]
https://lijiapeng001.github.io/2018/12/20/2019/ 

 新的一年..赚钱要紧赚钱要紧     &emsp;&emsp;从2017年12月份1号入职到现在有一年了，离开大姐的第一年，我有点想她。&emsp;&emsp;本来想了很多，也写了很多，jio得都是无关紧要的就全删了，今年是我过的节奏最快的一年，从17年暑假结束的第二天开始去培训学习，学完一周内找到工作，上班三个月公司倒闭，接着为了还房租继续找工作……记得上学时候非常抵触进入社会，连打工几乎都没去

**Comment by LiJiaPeng001** [comment]
女朋友真好看！

**Comment by wuhuisiyue** [comment]
已撸，听说这个是对女性最好的评价

**Comment by zhao-heng-sheng** [comment]
你莫不是个傻屌

**Comment by wzfeilongge** [comment]
以前叫李小鹏 现在叫李小朋
